image: node:6

cache:
  paths:
  - node_modules/

stages:
  - lint
  - build
test_lint:
  stage: lint
  script:
   - npm run lint
   
test_build:
  stage: build
  script:
   - npm install
   - npm run build

